///
/// A simple token class. These are generated by Lexer and consumed by Parser.
///
class Token {
	let type: TokenType
	let text: String

	init(_ type: TokenType, _ text: String) {
		self.type = type
		self.text = text
	}
}
